import CommunityWall from "./CommunityWall";
import { getRecentCommunityCards, getTopCommunityCards } from "@/lib/community";

export const metadata = {
  title: "Community | FutClaw",
  description: "Discover developer cards generated by the FutClaw community.",
};

export const revalidate = 60;

function mergeCards(cards: Awaited<ReturnType<typeof getRecentCommunityCards>>[]) {
  const seen = new Set<string>();
  return cards.flat().filter((card) => {
    const key = `${card.platform ?? "github"}:${card.login.toLowerCase()}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export default async function CommunityPage() {
  const [recentCards, topCards] = await Promise.all([
    getRecentCommunityCards(100),
    getTopCommunityCards(100),
  ]);
  const cards = mergeCards([recentCards, topCards]);
  return <CommunityWall cards={cards} initialVariant="dark" />;
}
